# Generated by Django 5.1.1 on 2024-11-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0005_imagecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecard',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
