# Generated by Django 5.1.1 on 2024-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0006_alter_imagecard_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCard',
        ),
        migrations.AddField(
            model_name='product',
            name='subname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
