# Generated by Django 5.1.1 on 2024-11-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0014_alter_product_apply_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
