# Generated by Django 5.1.1 on 2024-11-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0015_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
