# Generated by Django 5.1.1 on 2024-11-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0017_remove_product_apply_discount_remove_product_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apply_discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='subname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
