# Generated by Django 5.1.1 on 2024-12-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0019_product_owner_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/d1.jpg', upload_to='profile_pictures/'),
        ),
    ]
