# Generated by Django 5.1.1 on 2024-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0027_remove_product_image_remove_product_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
