# Generated by Django 5.1.1 on 2024-12-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0036_rename_purchase_date_purchaseditem_purchased_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseditem',
            name='user',
        ),
        migrations.DeleteModel(
            name='GiftCode',
        ),
        migrations.DeleteModel(
            name='PurchasedItem',
        ),
    ]
