# Generated by Django 5.1.1 on 2025-01-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0039_category_name_product_category_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='xsite.category'),
        ),
    ]
