# Generated by Django 5.1.1 on 2025-01-09 14:24

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0045_alter_product_price_alter_product_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(currency_choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları')], decimal_places=2, default_currency='TRY', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları')], default='TRY', editable=False, max_length=3),
        ),
    ]
