# Generated by Django 5.1.1 on 2025-05-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsite', '0047_alter_orderitem_order_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
